# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    hiwonder_xarm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

hiwonder_xarm_controller:
  ros__parameters:
    joints:
      - xarm_1_joint
      # - xarm_1_joint_mirror
      - xarm_2_joint
      - xarm_3_joint
      - xarm_4_joint
      - xarm_5_joint
      - xarm_6_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity