<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="xarm">

    <xacro:property name="chassis_length1" value="0.432"/>
    <xacro:property name="chassis_width1" value="0.432"/>
    <xacro:property name="chassis_height1" value="0.048"/>

    <!-- <xacro:property name="eef" value="eef_3_finger"/> -->
    <xacro:property name="eef" value="eef_2_finger"/>
    <xacro:arg name="sim_mode" default="true"/>
    <!-- <xacro:include filename="$(find autonomous_robot)/description/robot_dimensions.xacro"/> -->

    <!-- <xacro:include filename="$(find xarm_description)/urdf/xarm.urdf"/> -->
    <xacro:include filename="$(find xarm_description)/urdf/xarm_v3.urdf"/>
    <!-- <xacro:include filename="xarm_v2.urdf"/> -->
    <joint name="xarm_chassis" type="fixed">
        <parent link="chassis"/>
        <child link="xarm_base_link"/>
        <origin xyz="${chassis_length1/4+0.02} ${chassis_width1/4+0.02} ${chassis_height1}" rpy="0.0 0.0 -${pi/2}"/>
    </joint>
    
    <xacro:property name="sim_mode" value="true"/>
    <!-- <xacro:include filename="ros2_control.arm.xacro" /> -->
    <!-- <xacro:include filename="ros2_control.arm copy.xacro" /> -->
    <xacro:include filename="$(find xarm_description)/urdf/ros2_control.arm.xacro"/>
    
</robot>