# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    hiwonder_xarm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

hiwonder_xarm_controller:
  ros__parameters:
    joints:
      - xarm_1_joint
      # - xarm_1_joint_mirror
      - xarm_2_joint
      - xarm_3_joint
      - xarm_4_joint
      - xarm_5_joint
      - xarm_6_joint
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity


    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    # allow_partial_joints_goal: true
    # constraints:
    #   goal_time: 0.0

    # interpolation_method: linear

    
    
    # Trajectory constraints
    # set rate monitoring period to 10ms
    
    # state_publish_rate: 10.0  # Hz
    # action_monitor_rate: 5.0  # Hz


    # constraints:
    #   stopped_velocity_tolerance: 0.01
    #   goal_time: 0.0
    
    # # Allow partial goals
    # allow_partial_joints_goal: false
    
    # # Allow integrating velocity commands
    # allow_integration_in_place: false
    
    # # Trajectory execution parameters
    # allow_nonzero_velocity_at_trajectory_end: true